name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: cmake@v2
      with:
        cmakeVersion: '3.18.4'

    - name: Install dependencies
      run: sudo apt-get install -y cmake doxygen

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure

    - name: Generate Doxygen documentation
      if: success()
      run: cd build && make doc_doxygen

    - name: Deploy documentation
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
